apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-backend
  
  labels:
    app: notes-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app-backend
  template:
    metadata:
      labels:
        app: notes-app-backend
    spec:
      containers:
      - name: backend
        image: notes-app-backend:v5
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: DATABASE_URL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notes-app-secret
              key: POSTGRES_PASSWORD
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: OLLAMA_HOST
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/notes
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/notes
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: notes-data
          mountPath: /app/data
      volumes:
      - name: notes-data
        emptyDir: {}
