apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-init
  
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ollama-init
        image: ollama/ollama:latest
        command:
        - /bin/bash
        - -c
        - |
          # Wait for Ollama service to be ready
          sleep 30
          
          # Pull the smallest models
          echo "Pulling phi3:mini model..."
          ollama pull phi3:mini
          
          echo "Pulling nomic-embed-text model..."
          ollama pull nomic-embed-text
          
          echo "Models pulled successfully!"
          
          # List available models
          ollama list
        env:
        - name: OLLAMA_HOST
          value: "http://notes-app-ollama-service:11434"
      
